# Generated by Django 4.2.1 on 2023-05-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=10, verbose_name='管理员名称')),
                ('password', models.CharField(max_length=15, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=6, verbose_name='鞋产品种类')),
                ('picture', models.CharField(max_length=64, verbose_name='图片')),
                ('rank_link', models.CharField(max_length=64, verbose_name='榜单链接')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('occupation', models.CharField(max_length=10, verbose_name='职业')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.admin', verbose_name='管理员编号')),
            ],
        ),
        migrations.CreateModel(
            name='RecomKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.SmallIntegerField(choices=[(1, '运动鞋'), (2, '休闲鞋'), (3, '商务鞋'), (4, '高功能鞋')], verbose_name='关键字1')),
                ('key2', models.SmallIntegerField(choices=[(1, '时尚'), (2, '经典'), (3, '复古'), (4, '简约')], verbose_name='关键字2')),
                ('shoe_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.shoeproduct', verbose_name='鞋类产品id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='用户编号')),
            ],
        ),
    ]
