# Generated by Django 4.2.1 on 2023-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(1, '时尚'), (4, '简约'), (3, '复古'), (2, '经典')], verbose_name='关键字2'),
        ),
    ]
