# Generated by Django 4.2.1 on 2023-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_recomkey_key2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomkey',
            old_name='shoe_product_id',
            new_name='shoe_product',
        ),
        migrations.RenameField(
            model_name='recomkey',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(1, '时尚'), (4, '简约'), (2, '经典'), (3, '复古')], verbose_name='关键字2'),
        ),
    ]
