# Generated by Django 4.2.1 on 2023-05-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_shoe_product_id_recomkey_shoe_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(4, '简约'), (2, '经典'), (1, '时尚'), (3, '复古')], verbose_name='关键字2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.admin', verbose_name='管理员编号'),
        ),
    ]
