# Generated by Django 4.2.1 on 2023-05-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_recomkey_key2_alter_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomkey',
            name='key1',
            field=models.SmallIntegerField(choices=[(1035, '跑鞋'), (9914, '徒步鞋'), (1034, '足球鞋'), (1032, '篮球鞋'), (5853, '羽毛球鞋'), (10106, '轮滑鞋'), (10304, '综合训练鞋'), (1033, '舞蹈鞋'), (7429, '高尔夫球鞋'), (9906, '运动凉鞋')], verbose_name='关键字1'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(1, '时尚'), (2, '经典'), (3, '复古'), (4, '简约')], verbose_name='关键字2'),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='type',
            field=models.SmallIntegerField(choices=[(1035, '跑鞋'), (9914, '徒步鞋'), (1034, '足球鞋'), (1032, '篮球鞋'), (5853, '羽毛球鞋'), (10106, '轮滑鞋'), (10304, '综合训练鞋'), (1033, '舞蹈鞋'), (7429, '高尔夫球鞋'), (9906, '运动凉鞋')], verbose_name='鞋产品种类'),
        ),
    ]
