# Generated by Django 4.2.1 on 2023-05-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_shoeproduct_picture_shoeproduct_picture1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeproduct',
            name='details',
            field=models.TextField(default='暂无', verbose_name='产品类型描述'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(2, '经典'), (4, '简约'), (3, '复古'), (1, '时尚')], verbose_name='关键字2'),
        ),
    ]
