# Generated by Django 4.2.1 on 2023-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_recomkey_key2_alter_shoeproduct_picture2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoeproduct',
            name='details',
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='details1',
            field=models.TextField(default='暂无', verbose_name='产品类型描述1'),
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='details2',
            field=models.TextField(default='暂无', verbose_name='产品类型描述2'),
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='details3',
            field=models.TextField(default='暂无', verbose_name='产品类型描述3'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(2, '经典'), (3, '复古'), (1, '时尚'), (4, '简约')], verbose_name='关键字2'),
        ),
    ]
