# Generated by Django 4.2.1 on 2023-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_shoeproduct_details_shoeproduct_details1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(1, '时尚'), (3, '复古'), (4, '简约'), (2, '经典')], verbose_name='关键字2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=10, null=True, verbose_name='职业'),
        ),
    ]
