# Generated by Django 4.2.1 on 2023-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_admin_password_alter_recomkey_key2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(3, '复古'), (2, '经典'), (4, '简约'), (1, '时尚')], verbose_name='关键字2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_choice',
            field=models.SmallIntegerField(choices=[(1035, '跑鞋'), (9914, '徒步鞋'), (1034, '足球鞋'), (1032, '篮球鞋'), (5853, '羽毛球鞋'), (10106, '轮滑鞋'), (10304, '综合训练鞋'), (1033, '舞蹈鞋'), (7429, '高尔夫球鞋'), (9906, '运动凉鞋')], default=1035, null=True, verbose_name='上一次的选择'),
        ),
    ]
