# Generated by Django 4.2.1 on 2023-05-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_recomkey_key3_alter_recomkey_key1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomkey',
            name='band',
            field=models.CharField(max_length=10, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key1',
            field=models.SmallIntegerField(choices=[(1035, '跑鞋'), (9914, '徒步鞋'), (1032, '篮球鞋'), (1034, '足球鞋'), (5853, '羽毛球鞋'), (10106, '轮滑鞋'), (10304, '综合训练鞋'), (1033, '舞蹈鞋'), (7429, '高尔夫球鞋'), (9906, '运动凉鞋')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(2, '经典'), (1, '时尚'), (4, '简约'), (3, '复古'), (5, '奇异')], null=True, verbose_name='风格'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key3',
            field=models.SmallIntegerField(choices=[(2, '平价'), (3, '低价'), (1, '高级')], null=True, verbose_name='价位'),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30, verbose_name='广告商')),
                ('ad_picture', models.ImageField(upload_to='images/', verbose_name='广告图片')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='管理员id')),
            ],
        ),
    ]
