# Generated by Django 4.2.1 on 2023-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_recomkey_band_alter_recomkey_key1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(3, '复古'), (1, '时尚'), (2, '经典'), (4, '简约'), (5, '奇异')], null=True, verbose_name='风格'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key3',
            field=models.SmallIntegerField(choices=[(2, '平价'), (1, '高级'), (3, '低价')], null=True, verbose_name='价位'),
        ),
    ]
