# Generated by Django 4.2.1 on 2023-05-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alter_advertisement_admin_alter_recomkey_key2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(3, '复古'), (5, '奇异'), (2, '经典'), (4, '简约'), (1, '时尚')], null=True, verbose_name='风格'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='key3',
            field=models.SmallIntegerField(choices=[(3, '低价'), (2, '平价'), (1, '高级')], null=True, verbose_name='价位'),
        ),
        migrations.AlterField(
            model_name='recomkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', unique=True, verbose_name='用户编号'),
        ),
    ]
