# Generated by Django 4.2.1 on 2023-05-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_shoeproduct_admin_alter_recomkey_key2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomkey',
            name='key2',
            field=models.SmallIntegerField(choices=[(4, '简约'), (1, '时尚'), (5, '奇异'), (2, '经典'), (3, '复古')], null=True, verbose_name='风格'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
